import { defineLangTree } from "../Translate";

export const FormText = defineLangTree({
    UnknownError: {
        zh_CN: "未知错误",
        zh_TW: "未知錯誤",
        en_US: "Unknown error",
        ja_JP: "未知のエラー",
        fr_FR: "Erreur inconnue",
        de_DE: "Unbekannter Fehler",
        ko_KR: "알 수 없는 오류",
        es_ES: "Error desconocido",
    },
    TypeMisMatch: {
        zh_CN: "类型不匹配",
        zh_TW: "類型不匹配",
        en_US: "Type mismatch",
        ja_JP: "型の不一致",
        fr_FR: "Type incorrect",
        de_DE: "Typkonflikt",
        ko_KR: "타입 불일치",
        es_ES: "Tipo incorrecto",
    },
    TextFiled_NotString: {
        zh_CN: "必须是字符串",
        zh_TW: "必須是字串",
        en_US: "Must be a string",
        ja_JP: "文字列である必要があります",
        fr_FR: "Doit être une chaîne de caractères",
        de_DE: "Muss eine Zeichenkette sein",
        ko_KR: "문자열이어야 합니다",
        es_ES: "Debe ser una cadena de texto",
    },
    TextFiled_NotNumber: {
        zh_CN: "必须是数字",
        zh_TW: "必須是數字",
        en_US: "Must be a number",
        ja_JP: "数字である必要があります",
        fr_FR: "Doit être un nombre",
        de_DE: "Muss eine Zahl sein",
        ko_KR: "숫자여야 합니다",
        es_ES: "Debe ser un número",
    },
    ToggleFiled_NotBoolean: {
        zh_CN: "toggle值必须是布尔类型",
        zh_TW: "toggle值必須是布林類型",
        en_US: "Toggle value must be a boolean",
        ja_JP: "トグル値は真偽値である必要があります",
        fr_FR: "La valeur du bouton doit être un booléen",
        de_DE: "Umschaltwert muss ein boolescher Wert sein",
        ko_KR: "토글 값은 불리언 타입이어야 합니다",
        es_ES: "El valor del interruptor debe ser booleano",
    },
    Filed_Len_MisMatch: {
        zh_CN: "表单错误，长度不匹配",
        zh_TW: "表單錯誤，長度不匹配",
        en_US: "Form error, length mismatch",
        ja_JP: "フォームエラー：長さが一致しません",
        fr_FR: "Erreur de formulaire, la longueur ne correspond pas",
        de_DE: "Formularfehler, Länge stimmt nicht überein",
        ko_KR: "폼 오류: 길이가 일치하지 않습니다",
        es_ES: "Error en el formulario, la longitud no coincide",
    },
});
