import { defineLangTree } from "../Translate";

export const FormText = defineLangTree({
    // 基础校验
    Field_Empty: {
        zh_CN: "该项为必填项，不能为空",
        zh_TW: "該項為必填項，不能為空",
        en_US: "This field is required and cannot be empty",
        ja_JP: "この項目は必須であり、空白にすることはできません",
        fr_FR: "Ce champ est obligatoire et ne peut pas être vide",
        de_DE: "Dieses Feld ist erforderlich und darf nicht leer sein",
        ko_KR: "이 필드는 필수이며 비워 둘 수 없습니다",
        es_ES: "Este campo es obligatorio y no puede estar vacío",
    },
    // 数据解析错误 (精准提示)
    Error_InvalidString: {
        zh_CN: "数据格式异常：期待文本输入",
        zh_TW: "數據格式異常：期待文本輸入",
        en_US: "Data format error: Expected text input",
        ja_JP: "データ形式エラー：テキスト入力が必要です",
        fr_FR: "Erreur de format : Texte attendu",
        de_DE: "Datenformatfehler: Texteingabe erwartet",
        ko_KR: "데이터 형식 오류: 텍스트 입력이 필요합니다",
        es_ES: "Error de formato: se esperaba entrada de texto",
    },
    Error_InvalidNumber: {
        zh_CN: "请输入一个有效的数字",
        zh_TW: "請輸入一個有效的數字",
        en_US: "Please enter a valid number",
        ja_JP: "有効な数字を入力してください",
        fr_FR: "Veuillez entrer un nombre valide",
        de_DE: "Bitte geben Sie eine gültige Zahl ein",
        ko_KR: "유효한 숫자를 입력하십시오",
        es_ES: "Por favor, ingrese un número válido",
    },
    Error_InvalidToggle: {
        zh_CN: "开关状态异常",
        zh_TW: "開關狀態異常",
        en_US: "Invalid toggle state",
        ja_JP: "トグルの状態が無効です",
        fr_FR: "État du bouton non valide",
        de_DE: "Ungültiger Umschaltzustand",
        ko_KR: "토글 상태가 유효하지 않습니다",
        es_ES: "Estado de interruptor no válido",
    },
    Error_InvalidSlider: {
        zh_CN: "滑块数值异常",
        zh_TW: "滑塊數值異常",
        en_US: "Invalid slider value",
        ja_JP: "スライダーの値が無効です",
        fr_FR: "Valeur du curseur non valide",
        de_DE: "Ungültiger Schiebereglerwert",
        ko_KR: "슬라이더 값이 유효하지 않습니다",
        es_ES: "Valor de control deslizante no válido",
    },
    Error_InvalidDropdown: {
        zh_CN: "下拉框选择无效",
        zh_TW: "下拉框選擇無效",
        en_US: "Invalid selection in dropdown",
        ja_JP: "ドロップダウンの選択が無効です",
        fr_FR: "Sélection non valide dans la liste",
        de_DE: "Ungültige Auswahl im Dropdown-Menü",
        ko_KR: "드롭다운 선택이 유효하지 않습니다",
        es_ES: "Selección no válida en el menú desplegable",
    },
    // 系统级错误
    Field_valiErr: {
        zh_CN: "第 {index} 个输入项验证失败",
        zh_TW: "第 {index} 個輸入項驗證失敗",
        en_US: "Validation failed for input #{index}",
        ja_JP: "第 {index} 項目目の検証に失敗しました",
        fr_FR: "Échec de la validation pour l'entrée n°{index}",
        de_DE: "Validierung für Eingabe Nr. {index} fehlgeschlagen",
        ko_KR: "{index}번째 입력 항목 유효성 검사 실패",
        es_ES: "Error de validación en la entrada n.º {index}",
    },
    // 长度不匹配通常是开发阶段或由于表单动态生成的逻辑错误
    Filed_Len_MisMatch: {
        zh_CN: "表单处理异常：提交的数据量与预期不符",
        zh_TW: "表單處理異常：提交的數據量與預期不符",
        en_US: "Form Error: Submitted data length mismatch",
        ja_JP: "フォームエラー：送信されたデータの長さが一致しません",
        fr_FR: "Erreur de formulaire : longueur des données incorrecte",
        de_DE: "Formularfehler: Datenlänge stimmt nicht überein",
        ko_KR: "폼 오류: 제출된 데이터 길이가 일치하지 않습니다",
        es_ES: "Error de formulario: la longitud de los datos no coincide",
    },
    UnknownError: {
        zh_CN: "发生未知错误",
        zh_TW: "發生未知錯誤",
        en_US: "An unknown error occurred",
        ja_JP: "未知のエラーが発生しました",
        fr_FR: "Une erreur inconnue est survenue",
        de_DE: "Ein unbekannter Fehler ist aufgetreten",
        ko_KR: "알 수 없는 오류가 발생했습니다",
        es_ES: "Ocurrió un error desconocido",
    },
});
