name: Build dev

on:
    push:
        branches:
            - dev
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - name: Install Node dependencies
              run: npm ci

            - name: build
              run: npm run pack

            - name: Upload pack artifact
              uses: actions/upload-artifact@v5
              with:
                  name: dev-package
                  path: "*.tgz"
