name: Build

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22"

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install Node dependencies
              run: npm install

            - name: build
              run: npm run build:declare

            - name: Upload to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
                  files: build/**
